export enum OrderValidationErrors {
    EMPTY_EMAIL = 'Email cannot be empty.',
    EMAIL_LENGTH_VIOLATION = 'Email has to have length from 3 to 100.',
    EMAIL_INCORRECT_FORMAT = 'Email format is incorrect.',
    EMPTY_FIRST_NAME = 'First name cannot be empty.',
    FIRST_NAME_LENGTH_VIOLATION = 'First name has to have length from 2 to 100.',
    FIRST_NAME_INCORRECT_FORMAT = 'First name format is incorrect.',
    EMPTY_LAST_NAME = 'Last name cannot be empty.',
    LAST_NAME_LENGTH_VIOLATION = 'Last name has to have length from 2 to 100.',
    LAST_NAME_INCORRECT_FORMAT = 'Last name format is incorrect.',
    EMPTY_PHONE_NUMBER = 'Phone number cannot be empty.',
    PHONE_NUMBER_INCORRECT_FORMAT = 'Phone number format is incorrect.',
    EMPTY_COUNTRY = 'Country cannot be empty.',
    COUNTRY_DELIVERY_VIOLATION = 'Country has to be only Latvia, Lithuania, or Estonia.',
    EMPTY_CITY = 'City cannot be empty.',
    CITY_LENGTH_VIOLATION = 'City has to have length from 4 to 100.',
    CITY_INCORRECT_FORMAT = 'City has to contains letters. Can contains - and space between the words.',
    EMPTY_POSTAL_CODE = 'Postal code cannot be empty.',
    POSTAL_CODE_INCORRECT_FORMAT = 'Postal code format is incorrect. Country do not have any matches.',
    EMPTY_ADDRESS = 'Address cannot be empty.',
    SPECIAL_CHARACTERS_NOT_ALLOWED = 'Address cannot contains any special characters.',
    NO_SEARCH_CRITERIA = 'Invalid search criteria.',
}
